// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInAppPaintDotNet
{
    static class Vsix
    {
        public const string Id = "1F26AAE5-DA33-4D31-A5EB-AA424D745321";
        public const string Name = "Open in Paint.NET";
        public const string Description = @"Open multiple files simultaneously in Paint.NET directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.52";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, Paint.NET, Paint, PaintDotNet";
    }
}
