// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInAppPaintDotNet
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "123d2a90-f17c-4563-97e1-659f2cb16c7c";
        public const string guidOpenInVsCmdSetString = "16ded3d5-00b3-4444-a8cc-536fe62cefc9";
        public const string guidImagesString = "11fdde54-27fa-469f-8e59-92d457dc9e02";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);
        public static Guid guidOpenInVsCmdSet = new Guid(guidOpenInVsCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppFolderExplore = 0x1040;
        public const int CmdIdOpenInAppFolderExplore = 0x0110;
        public const int bmpPic1 = 0x0001;
    }
}
