// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2017Community
{
    static class Vsix
    {
        public const string Id = "077346DD-CC6F-4D46-BC6B-2634EE1720D0";
        public const string Name = "Open in Visual Studio 2017 Community";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2017 Community Edition directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.41";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, open in VS2017, VS2017, open in Visual Studio 2017, Visual Studio 2017, community";
    }
}
