// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInOpera
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "09010792-db21-4e33-8360-1c69d5cb5a9c";
        public const string guidOpenInVsCmdSetString = "a68dde41-d212-432c-a41c-0418274b06ea";
        public const string guidImagesString = "6fa0435d-f2e8-49eb-9dfa-2e598a4eb4ca";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);
        public static Guid guidOpenInVsCmdSet = new Guid(guidOpenInVsCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppFolderExplore = 0x1040;
        public const int CmdIdOpenInAppFolderExplore = 0x0110;
        public const int bmpPic1 = 0x0001;
    }
}
