version: 1.0.{build}
image: Visual Studio 2017
environment:
    my_encrypted_sonarqube_token:
        secure: 94Py9ytqrmqFVtmUiyayJJ4Hgg2vjF1+YuRJldGGWO82/9zEens+sCjeh7wzc2Le
install:
    - choco install "sonarscanner-msbuild-net46" -y
before_build:
    - cmd: nuget restore Src/OpenInApp.Launcher.sln
    - choco install opencover.portable
    - choco install codecov
    - SonarScanner.MSBuild.exe begin /k:"OpenInApp.Launcher" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%my_encrypted_sonarqube_token%" /d:"sonar.organization=gregtrevellick-github"
build:
    project: Src/OpenInApp.Launcher.sln
    verbosity: minimal
after_build:
    - SonarScanner.MSBuild.exe end /d:"sonar.login=%my_encrypted_sonarqube_token%"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
test_script:
- OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:".\src\OpenInApp.Common.Tests\bin\Debug\OpenInApp.Common.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[OpenInApp.Common.Tests*]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml"