// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2015
{
    static class Vsix
    {
        public const string Id = "51818B3F-32D2-4538-BB5B-73A4BEDCB8B5";
        public const string Name = "Open in Visual Studio 2015";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2015 directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.41";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, open in VS2015, VS2015, open in Visual Studio 2015, Visual Studio 2015";
    }
}
