// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2019Professional
{
    static class Vsix
    {
        public const string Id = "6962FBF6-8B06-4884-97DA-E07D208D89C5";
        public const string Name = "Open in Visual Studio 2019 Professional";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2019 Professional Edition directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.53";
        public const string Author = "Greg Trevellick";
        public const string Tags = "VS2019, Visual Studio 2019, Professional";
    }
}
