// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2019Professional
{
    static class Vsix
    {
        public const string Id = "4F2AA665-83D6-4646-9F40-2211748FBABD";
        public const string Name = "Open in Visual Studio 2019 Professional";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2019 Professional Edition directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.41";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, open in VS2019, VS2019, open in Visual Studio 2019, Visual Studio 2019, professional";
    }
}
