// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInXamarinStudio
{
    static class Vsix
    {
        public const string Id = "4ED1099A-F28F-4E06-A2C8-8C3D3277B9A7";
        public const string Name = "Open in Xamarin Studio";
        public const string Description = @"Open multiple files simultaneously in Xamarin Studio directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.5";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, Xamarin, Xamarin Studio, studio";
    }
}
