// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2017Professional
{
    static class Vsix
    {
        public const string Id = "4F2AA665-83D6-4646-9F40-2211748FBABD";
        public const string Name = "Open in Visual Studio 2017 Professional";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2017 Professional Edition directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.52";
        public const string Author = "GregTrevellick";
        public const string Tags = "VS2017, Visual Studio 2017, Professional";
    }
}
