// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInAndroidStudio
{
    static class Vsix
    {
        public const string Id = "5bba97c5-4b25-491d-a209-6d0f2e33a8fc";
        public const string Name = "Open in Android Studio";
        public const string Description = @"Open multiple files simultaneously in Android Studio directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.43";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, Android Studio, Android";
    }
}
