// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2019Community
{
    static class Vsix
    {
        public const string Id = "DF1DFCDF-E0AD-4084-B535-662FC94748BA";
        public const string Name = "Open in Visual Studio 2019 Community";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2019 Community Edition directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.53";
        public const string Author = "Greg Trevellick";
        public const string Tags = "VS2019, Visual Studio 2019, Community";
    }
}
