// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInWinDirStat
{
    static class Vsix
    {
        public const string Id = "28271687-b479-4a4e-aa2e-23085737a230";
        public const string Name = "Open in WinDirStat";
        public const string Description = @"Open multiple folders simultaneously in WinDirStat directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.27";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, WinDirStat";
    }
}
