// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInTreeSizeProfessional
{
    static class Vsix
    {
        public const string Id = "a1b88397-2308-43ac-a471-6c1936720a6f";
        public const string Name = "Open in TreeSize Professional";
        public const string Description = @"Open multiple folders simultaneously in TreeSize Professional directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.52";
        public const string Author = "GregTrevellick";
        public const string Tags = "TreeSize, TreeSizeProfessional, disc space";
    }
}
