// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInTreeSizeProfessional
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "82aedca6-9734-4dab-aa7e-1eb6c2ea6014";
        public const string guidOpenInVsCmdSetString = "51cc1362-450a-4cb1-91dd-6b550918a201";
        public const string guidImagesString = "b7908f9b-bb36-4de5-84db-2e456918e11b";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);
        public static Guid guidOpenInVsCmdSet = new Guid(guidOpenInVsCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppItemNode = 0x1040;
        public const int CmdIdOpenInAppItemNode = 0x0110;
        public const int GroupOpenInAppFolderNode = 0x1050;
        public const int CmdIdOpenInAppFolderNode = 0x0120;
        public const int GroupOpenInAppProject = 0x1060;
        public const int CmdIdOpenInAppProject = 0x0130;
        public const int bmpPic1 = 0x0001;
    }
}
