// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2017Enterprise
{
    static class Vsix
    {
        public const string Id = "348687B9-1B76-47EB-931C-1605660E3D7B";
        public const string Name = "Open in Visual Studio 2017 Enterprise";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2017 Enterprise Edition directly from Solution Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.1.1";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, open in VS2017, VS2017, open in Visual Studio 2017, Visual Studio 2017, enterprise";
    }
}
