// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2019Enterprise
{
    static class Vsix
    {
        public const string Id = "348687B9-1B76-47EB-931C-1605660E3D7B";
        public const string Name = "Open in Visual Studio 2019 Enterprise";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2019 Enterprise Edition directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.41";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, open in VS2019, VS2019, open in Visual Studio 2019, Visual Studio 2019, enterprise";
    }
}
