// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInSQLServerManagementStudio
{
    static class Vsix
    {
        public const string Id = "ae571a7d-4421-40a0-bf5d-e58baf00a57d";
        public const string Name = "Open in SQL Server Management Studio";
        public const string Description = @"Open multiple files simultaneously in SQL Server Management Studio directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.30";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, Sequel Server, Sequel Server Management Studio, SQL Server, SQL Server Management Studio, SSMS, ";
    }
}
