// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVivaldi
{
    static class Vsix
    {
        public const string Id = "AEAAB1BF-8A84-481B-A113-C823E9EC95BC";
        public const string Name = "Open in Vivaldi";
        public const string Description = @"Open multiple files simultaneously in Vivaldi web browser directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.2";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, Vivaldi";
    }
}
