// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInFirefoxDeveloperEdition
{
    static class Vsix
    {
        public const string Id = "44EC5BEA-981F-45FB-A489-75F838CCD812";
        public const string Name = "Open in Firefox Developer Edition";
        public const string Description = @"Open multiple files simultaneously in Firefox Developer Edition directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.9";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, Firefox Developer Edition, Firefox, Mozilla";
    }
}
