// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInFirefoxDeveloperEdition
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "bc91becb-dffc-43e5-bbc7-b2777033bcb4";
        public const string guidOpenInVsCmdSetString = "01fb05e5-1afc-4989-8c5c-3c9c80ea2fd8";
        public const string guidImagesString = "19bae533-ee1f-402e-b451-809548972bcf";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);
        public static Guid guidOpenInVsCmdSet = new Guid(guidOpenInVsCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppItemNode = 0x1040;
        public const int CmdIdOpenInAppItemNode = 0x0110;
        public const int bmpPic1 = 0x0001;
    }
}
