// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2012
{
    static class Vsix
    {
        public const string Id = "4F1F19BB-1F05-4D64-9053-A35BD4A634B5";
        public const string Name = "Open in Visual Studio 2012";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2012 directly from Solution Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.1.1";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, open in VS2012, VS2012, open in Visual Studio 2012, Visual Studio 2012";
    }
}
