// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInAppAltovaXmlSpy
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "62a5a896-9442-4aa3-a87c-0daece0e04a5";
        public const string guidOpenInVsCmdSetString = "82afac2b-5d6f-43f7-8c37-c575653bc07c";
        public const string guidImagesString = "90ece3e2-9811-460b-a9c1-0d9ec151cf74";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);
        public static Guid guidOpenInVsCmdSet = new Guid(guidOpenInVsCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppItemNode = 0x1040;
        public const int CmdIdOpenInAppItemNode = 0x0110;
        public const int GroupOpenInAppFolderNode = 0x1050;
        public const int CmdIdOpenInAppFolderNode = 0x0120;
        public const int GroupOpenInAppProjNode = 0x1060;
        public const int CmdIdOpenInAppProjNode = 0x0130;
        public const int bmpPic1 = 0x0001;
    }
}
