// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInChromeCanary
{
    static class Vsix
    {
        public const string Id = "2B0F2EE6-6EBD-4DF2-A8F7-650D312C6230";
        public const string Name = "Open in Chrome Canary";
        public const string Description = @"Open multiple files simultaneously in Chrome Canary directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.9";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, chrome, canary";
    }
}
