// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInEmacs
{
    static class Vsix
    {
        public const string Id = "CF1D7CEE-7F85-44E5-A4E3-9213877B8EBF";
        public const string Name = "Open in Emacs";
        public const string Description = @"Open multiple files simultaneously in Emacs directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.40";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, emacs";
    }
}
