// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInEmacs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "338c3988-6cbc-429e-b24c-7a1a2709ec23";
        public const string guidOpenInVsCmdSetString = "86571752-9143-4ce0-88e5-1c93dedf330b";
        public const string guidImagesString = "9a9fccea-c1fc-4fda-b80b-2924e571538b";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);
        public static Guid guidOpenInVsCmdSet = new Guid(guidOpenInVsCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppFolderExplore = 0x1040;
        public const int CmdIdOpenInAppFolderExplore = 0x0110;
        public const int bmpPic1 = 0x0001;
    }
}
