// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInAppGimp
{
    static class Vsix
    {
        public const string Id = "AE977542-57A6-448A-89FB-A0915C592A6E";
        public const string Name = "Open in GIMP - GNU Image Manipulation Program";
        public const string Description = @"Open multiple files simultaneously in GIMP (GNU Image Manipulation Program) directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.51";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, gimp, GNU Image Manipulation Program";
    }
}
