// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInAppMarkdownMonster
{
    static class Vsix
    {
        public const string Id = "MFA20CC7-7C8E-4E41-B258-539C067E5649";
        public const string Name = "Open in Markdown Monster";
        public const string Description = @"Open multiple files simultaneously in Markdown Monster directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.35";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, MarkdownMonster, Markdown Monster, Markdown";
    }
}
