// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInAtom
{
    static class Vsix
    {
        public const string Id = "014f77d0-8a75-4421-b484-5fc73bca99d7";
        public const string Name = "Open in Atom";
        public const string Description = @"Open multiple files simultaneously in Atom directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.43";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, Atom";
    }
}
