// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInTreeSizeFree
{
    static class Vsix
    {
        public const string Id = "0597a0d5-0bfc-44a5-924c-b556c5047018";
        public const string Name = "Open in TreeSize Free";
        public const string Description = @"Open multiple folders simultaneously in TreeSize Free directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.52";
        public const string Author = "GregTrevellick";
        public const string Tags = "open in, TreeSize, TreeSizeFree, disc space";
    }
}
