// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInAppAltovaXmlSpy
{
    static class Vsix
    {
        public const string Id = "AE643C9F-EA6E-4A88-A122-34696D103F82";
        public const string Name = "Open in Altova XMLSpy";
        public const string Description = @"Open multiple files simultaneously in Altova XMLSpy XML Editor directly from Solution Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "GregTrevellick";
        public const string Tags = "xml, xmlspy, altova, xsd, xslt, open, open in";
    }
}
