// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2013
{
    static class Vsix
    {
        public const string Id = "4EE49344-F83F-40D8-9901-79C6D5673B71";
        public const string Name = "Open in Visual Studio 2013";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2013 directly from Solution Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.1.6";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, open in VS2013, VS2013, open in Visual Studio 2013, Visual Studio 2013";
    }
}
