// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVS2013
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "5334e39c-dab6-4f43-b16e-835614f3fcb8";
        public const string guidOpenInVsCmdSetString = "d1502f9f-e878-4525-bbd5-f22171e020bd";
        public const string guidImagesString = "0725a0be-ab08-41c3-9ba9-96e1064b9947";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);
        public static Guid guidOpenInVsCmdSet = new Guid(guidOpenInVsCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppItemNode = 0x1040;
        public const int CmdIdOpenInAppItemNode = 0x0110;
        public const int GroupOpenInAppFolderNode = 0x1050;
        public const int CmdIdOpenInAppFolderNode = 0x0120;
        public const int GroupOpenInAppProjNode = 0x1060;
        public const int CmdIdOpenInAppProjNode = 0x0130;
        public const int bmpPic1 = 0x0001;
    }
}
