// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInOperaDeveloper
{
    static class Vsix
    {
        public const string Id = "2580C34C-5E76-458E-8C78-E216117C094A";
        public const string Name = "Open in Opera Developer";
        public const string Description = @"Open multiple files simultaneously in Opera Developer directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.5";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, opera";
    }
}
