// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInOperaDeveloper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "4ebaf7ed-02c8-4afa-8023-a0a995ff3600";
        public const string guidOpenInVsCmdSetString = "7e4d77ea-f610-4302-89d9-2188b97a2ce9";
        public const string guidImagesString = "2cd71d9f-0766-4be5-b42b-c918f370ea43";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);
        public static Guid guidOpenInVsCmdSet = new Guid(guidOpenInVsCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppFolderExplore = 0x1040;
        public const int CmdIdOpenInAppFolderExplore = 0x0110;
        public const int bmpPic1 = 0x0001;
    }
}
