// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInMSPaint
{
    static class Vsix
    {
        public const string Id = "D0F310D5-6CEF-40F7-9F93-4575C0326159";
        public const string Name = "Open in MS Paint";
        public const string Description = @"Open multiple files simultaneously in MS Paint directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.1.41";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, mspaint, ms paint";
    }
}
